### ISSUE TITLE
get_nasdaq_symbols error

### ISSUE THREAD

**Issue by aprestoncsm** [skillachie/finsymbols#19]
I'm using Python 2.7 and I'm having an issue with get_nasdaq_symbols (see error below). I can get the sp500/amex/nyse symbols just fine with your code, but nasdaq seems to be a problem. The error is:

Traceback (most recent call last):
  File "test.py", line 56, in <module>
    smbs=finsymbols.get_nasdaq_symbols()
  File "C:\Python27\lib\site-packages\finsymbols\symbols.py", line 51, in get_nasdaq_symbols
    return _get_exchange_data("NASDAQ")
  File "C:\Python27\lib\site-packages\finsymbols\symbols.py", line 64, in _get_exchange_data
    return get_symbol_list(symbol_data, exchange)
  File "C:\Python27\lib\site-packages\finsymbols\symbol_helper.py", line 28, in get_symbol_list
    symbol_data_dict['company'] = row[1]
IndexError: list index out of range
Press any key to continue . . .

My code is:

import finsymbols
smbs=finsymbols.get_nasdaq_symbols()

**Comment by skillachie** [comment]
Hi aprestoncsm,

Upgrade to the latest version using pip and do the following:

`
from finsymbols import symbols
from pprint import pprint

nasdaq_syms= symbols.get_nasdaq_symbols()
pprint(nasdaq_syms)
`

Let me know

**Comment by aprestoncsm** [comment]
That worked, thanks!
