### ISSUE TITLE
Error message when trying to get S&P500 symbols

### ISSUE THREAD

**Issue by vhriebes** [skillachie/finsymbols#21]
I'm trying to download the symbols for the S&P500 in python using finsymbols. This is my code:

from finsymbols import symbols
sp500 = symbols.get_sp500_symbols()

I'm getting this error: 

sp500 = symbols.get_sp500_symbols()
Traceback (most recent call last):

  File "<ipython-input-12-fed33dcab4ed>", line 1, in <module>
    sp500 = symbols.get_sp500_symbols()

  File "C:\Anaconda3\lib\site-packages\finsymbols\symbols.py", line 8, in get_sp500_symbols
    page_html = wiki_html('List_of_S%26P_500_companies', 'SP500.html')

  File "C:\Anaconda3\lib\site-packages\finsymbols\symbol_helper.py", line 95, in wiki_html
    save_file(file_path, wiki_html)

  File "C:\Anaconda3\lib\site-packages\finsymbols\symbol_helper.py", line 39, in save_file
    saved_file.write(file_data)

  File "C:\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 528521: character maps to <undefined>

Is there anything I can do to fix this? I'm using Anaconda 5.0.0 with Python 3.6 on a Windows 8. Thanks for the help!

**Comment by shlomiku** [comment]
I'm having the same issue. problem is here:
![image](https://user-images.githubusercontent.com/7924802/43888574-af8c91c8-9bca-11e8-9e1a-18c09e105edc.png)


since it is a str it tries to save it and get the issue you got.
the solution is in the second part. if doing 
```
 with open(file_path, "wb") as saved_file:
            saved_file.write(file_data.encode('utf-8'))
```
it works. so you can change locally, or the owner can release a fix for it
